- name: Copying repo
  ansible.builtin.copy:
    src: mongo.repo 
    dest: /etc/yum.repos.d/mongodb.repo
    # the source of file is on local drive , so NO need of remote_src

- name: install mongobd
  ansible.builtin.package:
    name: mongodb-org
    state: present

# to search and replace the ip adress

- name: Replace old IP with new
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

# start service and run

  # start service  and enable service
- name: Restarting mongodb
  ansible.builtin.service:
    name: mongodb
    state: restarted
    enabled: yes

# download schema
- name: download and extract mongodb schema 
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes
    # remote_src option is required when performing copy on remote
  
#inject schema. runs a .js file containing MongodB commands
- name: loading users schema 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes

- name: loading catalogue schema 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/caalogue.js"
    idempotent: yes