- name: Demo of variables
  hosts: all
  vars:
    URL: play.google.com  #global variable if declared here
  tasks:
    - name: printing the URL Task
      ansible.builtin.debug:
        msg: The value of url is {{URL}}
      

    - name: printing the URL from the Task
      ansible.builtin.debug:
        msg: The value of url is {{URL}}
      vars:
        URL: task.google.com   # varibale declared at task level; will super seed the global variable

    - name: printing the URL from the Task
      ansible.builtin.debug:
        msg: "{{URL}}" # when printing only varibale without comments, it should be given in quotes
      vars:
        URL: task.google.com   # varibale declared at task level; will super seed the global variable
    
    - name: printing the URL by input from the command line
      ansible.builtin.debug:
        msg: "{{CMD_URL}}" # when printing only varibale without comments, it should be given in quotes
    
    #ansible-playbook -i inv -e CMD_URL=cli.google.com ansible_user=centos -e ansible_password=DevOps321 01-playbook.yaml