# when to execute if appropriate Model is not available - if a packeage is not on Ansible
- name: Demo of using register 
  hosts: all
  tasks:
  - name: demo using shell Modeule
    ansible.builtin.shell: uptime
    register : OUT  # any name of a variable

  - name: Print the OUT register
    ansible.builtin.debug:
     msg: "{{OUT.stdout}}"

  - name: Printing th eexit code RC from Uptime command
    ansible.builtin.set_fact:
     STATUS_CODE: "{{OUT.rc}}"

  - name: Printing th eexit code RC from Uptime command
    ansible.builtin.debug:
     msg: "{{OUT.rc}}"


# The output is not as expected. Need to register the output
