- name: check if service is running or not
  hosts: all
  tasks:
  - name: check Nginx is running or not
    ansible.builtin.shell: ps -ef | grep nginx | grep-v grep
    ignore_errors: yes

  - name: Starting Nginx
    ansible.builtin.debug: 
      msg: starting Nginx server

# as Nginx is not running , it throws an error; but the YAML script is ok. so, use ignore_errors= yes as continue with script execution

