- name: check if service is running or not
  hosts: all
  vars:
    action: true
  tasks:
  - name: Execute when  distribution in CentOs
    ansible.builtin.debug:
      msg: welcome to CentOs
    when: ansible_distribution == "CentOS"
  
  - name: Execute when  distribution in CentOs
    ansible.builtin.debug:
      msg: welcome to Ubuntu
    when: ansible_distribution == "Ubuntu"

  - name: Run the action
    ansible.builtin.debug:
      msg: action is true
    when: action
    # wil execute the above code as the action is set to true.

  - name: Run this task when the variable is not declared
    ansible.builtin.debug:
      msg: Variable Action is Not defined
    when: action123 is not defined
    #  as the variable is not defined, the above will be executed
    # defined, not defined, true, false, succeed, failure are predefined key words
    # Ref : https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html
    