- name: check if service is running or not
  hosts: all
  tasks:
  - name: Execute when  distribution in CentOs
    ansible.builtin.debug:
      msg: welcome to CentOs
    when: ansible_distribution == "CentOS"
  
  - name: Execute when  distribution in CentOs
    ansible.builtin.debug:
      msg: welcome to Ubuntu
    when: ansible_distribution == "Ubuntu"