- name: Demo on tags 
  hosts: all
  tasks:
    - name: This is frontend task
      ansible.builtin.debug:
        msg: Installing Frontend
      tags: frontend

    - name: This is MongodB task
      ansible.builtin.debug:
        msg: Installing MongodB
      tags: MongodB

    - name: This is User task
      ansible.builtin.debug:
        msg: Installing User
      tags: user

    - name: This is cart task
      ansible.builtin.debug:
        msg: Installing cart
      tags: cart

# to execute commands on specific instances based on tag value. the command is as below
# gp ; ansible-playbook -1 inv -e ansible_user=Centos -e ansible_password=DevOps321 07-tags.yaml -t frontend