- name: Demo on Priviledge escalation
  hosts: all
  becaome: yes    # runs all the tasks  as root user
  tasks:
  - name: check user id
    ansible.builtin.shell: id
    register: OUT

  - name: Printing
    ansible.builtin.debug:
      msg: "{{OUT}}"