- name: Demo on Priviledge escalation
  hosts: all
  become: yes    # runs all the tasks  as root user
  tasks:
  - name: check user id
    ansible.builtin.shell: id
    register: OUT

  - name: Printing
    ansible.builtin.debug:
      msg: "{{OUT}}"

  - name: check user id
    ansible.builtin.shell: id
    register: OUT1
    become_user: centos

  - name: Printing
    ansible.builtin.debug:
      msg: "{{OUT1}}"