- name: Demo on loops
  hosts: all
  tasks:  
    -name: Demo on using loops 
      ansible.builtin.debug:
        msg: "Value is {{item}}"  # iten is a ansible keyword for items in the loop
      loop: 
        -10
        -20
        -30

# Each item is referred as iten in ansible