- name: Demo on package installation
  hosts: all
  become: yes  #priviledge escalation , to intall nginx as root user
  tasks: 
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    # state : present - if package is not there to install.  latest - to update the package ; absent - to remove package