- name: playbook to setup roboshop project
  become: yes
  hosts: "{{COMPONENT}}"    # not to hard code it 
  roles:
    - "{{COMPONENT}}"
  
  # so when running the command; provide the input on the command line
  # gp ; ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 -e COMPONENT=mongodb robot.yml
  