- name: configurring Node Js repo 
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: install node JS 
  ansible.builtin.package:
    name: nodejs  
    state: present

# creating roboshop user account
- name: creating a roboshop user account 
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop User account
